### ISSUE TITLE
[Bug]: Cannot connect to Dataverse

### ISSUE THREAD

**Issue by azeemnawaz12** [Power-Maverick/DataverseDevTools-VSCode#119]
### What happened?

Dataverse DevTools: Error occured - undefined. Please report it on GitHub.[](url)

![image](https://github.com/Power-Maverick/DataverseDevTools-VSCode/assets/5208522/4f3caa74-9648-4426-989e-37e60794c9fe)

### What version of the tool are you using?

v2.1.4

### What version of Visual Studio Code are you running?

1.78.2

### Any relevant session id from VSCode?

66dfa072-4166-464a-bf93-10d145ecda571685258787767

### Relevant log output

```shell
Error occured in connectDataverse command. 
Error code: undefined. 
Error message: undefined. 
Error stack: undefined.
```

**Comment by SescoEnvDev** [comment]
I've had the same issue with username/password, Windows Prompt, and Azure authentication

What version of the tool are you using?
v2.1.4

What version of Visual Studio Code are you running?
1.81.0-insider

**Comment by aicangas** [comment]
Hello, since today an error has happened to me. All the connections that I had have disappeared. And when I try to add a new connection I get the following error. See screenshot.
I have installed visual code again in case that was the problem.
Thanks
![image](https://github.com/Power-Maverick/DataverseDevTools-VSCode/assets/86791575/074e0eaa-c2f3-4866-8c20-2b3284b6b25d)

**Comment by Power-Maverick** [comment]
Issue should be resolved now. Make sure that v2.1.10 is installed.
